### ISSUE TITLE
Convert Receive Address to Simple Address

### ISSUE THREAD

**Issue by gaia** [greenaddress/WalletElectron#12]
is it possible to convert a standard receiving address to a simple address? thanks

**Comment by jgriffiths** [comment]
Hi,

What do you mean by "simple address"? The receiving addresses are multisig p2sh addresses (usualy wrapped as p2sh-p2wsh segwit addresses), the wallet doesn't support p2pkh since those can't support multisig (and therefore 2fa/limits security).

Please reopen with more information if the above doesn't answer your question.
